name: medical_app
description: Sistema de Gestión de Clínica Multiplataforma.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  responsive_framework: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Outfit
  #     fonts:
  #       - asset: assets/fonts/Outfit-Bold.ttf
  #         weight: 700
